---
title: "R_analysis.Rmd"
author: "mcdevitt"
date: "23 avril 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r custom model, echo = TRUE, message = FALSE}

# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ...	base model on all candidate features
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

	homes_subset <- homes_subset_base

	df_fits <- data.frame(row = integer(0),
						  feature = character(0),
						  type = character(0), 
						  r_squared = numeric(0),
						  stringsAsFactors = FALSE)
	
	for (i in 1 : (length(homes_subset)))
	{
			fit <- lm(homes_subset$log_saleprice ~ homes[,i])
			
			print(sprintf(" ... %3d : %20s | %10s | r^2 = %8.3f | p-value = %12.4e",
						  i, names(homes_subset[i]), class(homes_subset[,i]), summary(fit)$r.squared,
						  		summary(fit)$coefficients[,4][2] ))
			
			next_row <- data.frame(row = i, feature = names(homes_subset[i]), type = class(homes_subset[,i]),
								   r_squared = summary(fit)$r.squared)
			df_fits <- rbind(df_fits, next_row)
	}

	df_sort <- df_fits[with(df_fits, order(-r_squared)), ]
	
	df_sort
	
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ...	do some feature reduction based on VIF
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
	
	homes_subset <- homes_subset_base
	
	fit_all <- lm (log_saleprice ~ ., data = homes_subset)
	
	vif_lst <- vif(fit_all)
	vif_lst[order(vif_lst)]

	iter <- 1
	
	while ( vif_lst[order(-vif_lst[,1]),][1] > 5)
	{
		rmv_col <- order(-vif_lst[,1])[1]

				prnt_line <- paste(iter, "remove column :",
					   names(homes_subset)[[rmv_col]],
						"VIF = ", round(vif_lst[order(-vif_lst[,1]),][1], 2))

		print (prnt_line)
   
		homes_subset[, rmv_col] = NULL
		
		fit_all <- lm (log_saleprice ~ .,
						data = homes_subset)
		
		summary(fit_all)
		
		vif_lst <- vif(fit_all)
		vif_lst[order(vif_lst)]
	
		iter <- iter + 1
	}
	
	cat ("\n-=-=-=-=-=   Colinearity reduced   -=-=-=-=-=-=\n")
	
	names (homes_subset)
	
	fit_all <- lm (log_saleprice ~ .,
						data = homes_subset)
	
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ...	plot some residuals and influence diagnostics plots
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

	png(filename = "custom_model.png", width = 2200, height = 1100, units = "px")
	
	par (mfrow = c (2, 2))
	
	resid <- predict(fit_all) - homes_subset$log_saleprice
	hist(resid)	
	plot(predict(fit_all) - homes_subset$log_saleprice, main = "Residuals by Observation")
	plot(predict(fit_all) ~ homes_subset$log_saleprice, main = "Predicted log(Sale Price) vs. Train Set log(Sale Price)")

# Influential Observations - Cook's D plot

	cooks_d = cooks.distance(fit_all)
	plot(cooks_d, ylab = "Cooks distances", main = "Cook_s Distances")

	dev.off()	
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ...	test cases
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
	
	setwd(data_dir)
	test_homes <- read.csv("test.csv", stringsAsFactors = FALSE)
	setwd(home_dir)
	
	names(test_homes) <- tolower(names(test_homes))
	
	for (i in 2:(length(test_homes)))
	{
		if (class(test_homes[,i]) == "character")
		{
			test_homes[,i] <- factor (test_homes[,i])
		}
	}

	plot(predict(fit_all, newdata = test_homes))
	
	test_homes$pred_log_saleprice <- predict(fit_all, newdata = test_homes)
	
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ...	submittal file
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

	df_submit <- data.frame(test_homes$id, exp(test_homes$pred_log_saleprice))
	names(df_submit) <- c("Id", "SalePrice")
	
	df_submit$SalePrice[is.na(df_submit$SalePrice)] <- median(df_submit$SalePrice, na.rm = TRUE)

	write.csv(df_submit, file = "submit_test_pred_custom.csv", row.names = FALSE)
	
```

```{r forward, include = FALSE, message = FALSE}
	
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#  ...	Stepwise Regression - Forward
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

library (MASS)
	
	homes_subset <- homes_subset_base

	fit_forward <- lm (log_saleprice ~ ., data = homes_subset)
	
	AIC(fit_forward)
	
	step_fwd <- stepAIC(fit_forward, direction = "forward")
	
	step_fwd$anova # display results 
	
	plot(predict(step_fwd, newdata = test_homes))
	
	test_homes$pred_fwd_log_saleprice <- predict(step_fwd, newdata = test_homes)
	
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ...	submittal file - forward selection
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

	df_submit_fwd <- data.frame(test_homes$id, exp(test_homes$pred_fwd_log_saleprice))
	names(df_submit_fwd) <- c("Id", "SalePrice")
	
	df_submit_fwd$SalePrice[is.na(df_submit_fwd$SalePrice)] <- median(df_submit_fwd$SalePrice, na.rm = TRUE)

	write.csv(df_submit_fwd, file = "submit_test_pred_fwd_selection.csv", row.names = FALSE)

```

```{r backward, include = FALSE, message = FALSE}

# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#  ...	Stepwise Regression - Backward
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
	
	homes_subset <- homes_subset_base

	fit_backward <- lm (log_saleprice ~ ., data = homes_subset)
	step <- stepAIC(fit_backward, direction = "backward")
	step$anova # display results 
	
	plot(predict(fit_backward, newdata = test_homes))
	
	test_homes$pred_bwd_log_saleprice <- predict(fit_backward, newdata = test_homes)
	
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ...	submittal file - backward selection
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

	df_submit_bwd <- data.frame(test_homes$id, exp(test_homes$pred_bwd_log_saleprice))
	names(df_submit_bwd) <- c("Id", "SalePrice")
	
	df_submit_bwd$SalePrice[is.na(df_submit_bwd$SalePrice)] <- median(df_submit_bwd$SalePrice, na.rm = TRUE)

	write.csv(df_submit_bwd, file = "submit_test_pred_bwd_selection.csv", row.names = FALSE)

```

```{r stepwise, include = FALSE, message = FALSE}

# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#  ...	Stepwise Regression - both
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

library (MASS)
	
	homes_subset <- homes_subset_base

	fit_both <- lm (log_saleprice ~ ., data = homes_subset)
	step <- stepAIC(fit_both, direction = "both")
	step$anova # display results 
	
	plot(predict(fit_both, newdata = test_homes))
	plot(predict(fit_both) ~ homes_subset$log_saleprice,
			main = "Predicted log(Sale Price) vs. Train Set log(Sale Price)")

	
	test_homes$pred_both_log_saleprice <- predict(fit_both, newdata = test_homes)
	
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ...	submittal file - both selection
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

	df_submit_both <- data.frame(test_homes$id, exp(test_homes$pred_both_log_saleprice))
	names(df_submit_both) <- c("Id", "SalePrice")
	
	df_submit_both$SalePrice[is.na(df_submit_both$SalePrice)] <- median(df_submit_both$SalePrice, na.rm = TRUE)

	write.csv(df_submit_both, file = "submit_test_pred_both_selection.csv", row.names = FALSE)

```



```{r model of models, include = TRUE, message = FALSE}

# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#  ...	recommender model based on gln models
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

	df_mom <- subset(homes_subset_base, select = c(log_saleprice))

	pred_sas_fwd <- data.frame(predict(fit_sas_fwd))
	pred_both <- predict(fit_both)

	df_mom <- cbind (df_mom, pred_sas_fwd, pred_both)
	
	fit_mom <- lm (log_saleprice ~ ., data = df_mom)

	plot(predict(fit_mom, newdata = test_homes))
	
	plot(predict(fit_mom) ~ homes_subset$log_saleprice,
			main = "Predicted log(Sale Price) vs. Train Set log(Sale Price)")

	plot(predict(fit_mom) ~ predict(fit_both),
			main = "Predicted log(Sale Price) vs. Predicted log(Sale Price)")
	
	test_homes$pred_mom_log_saleprice <- predict(fit_mom, newdata = test_homes)
	
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ...	submittal file - mom selection
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

	df_submit_mom <- data.frame(test_homes$id, exp(test_homes$pred_mom_log_saleprice))
	names(df_submit_mom) <- c("Id", "SalePrice")
	
	df_submit_mom$SalePrice[is.na(df_submit_mom$SalePrice)] <- median(df_submit_mom$SalePrice, na.rm = TRUE)

	write.csv(df_submit_mom, file = "submit_test_pred_mom_selection.csv", row.names = FALSE)

```
