---
title: "ames iowa kaggle home price modeling"
author: "preeti swaminathan & patrick mcdevitt"
date: "14 avril 2017"
output: pdf_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

rm(list=ls())

library(ggplot2)
library(MASS)
library(car)

home_dir <- "~/_smu/_src/home_prices/"
setwd(home_dir)

data_dir <- "./data"


```

## House Prices - à la Kaggle - Homework 13

###Analysis Question 2  


  
```{r read data, include = TRUE, message = FALSE}

	setwd(home_dir)
	setwd(data_dir)

	homes <- read.csv("train.csv", stringsAsFactors = FALSE)
	setwd(home_dir)

	names(homes) <- tolower(names(homes))
	
	for (i in 2:(length(homes)))
	{
		if (class(homes[,i]) == "character")
		{
			homes[,i] <- factor (homes[,i])
		}
	}
```

```{r remove outliers, include = TRUE, message = FALSE}

# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ...	remove outliers ... more than 5 sigma from mean value
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
	
	lst <- length(homes) - 1	# sale price is (currently) last column
	
	for (i in 2 : lst)
	{
		if(class(homes[,i]) == "integer" || class(homes[,i]) == "numeric")
		{
			homes[,i][which(scale(homes[,i]) > 5)] <- NA
			homes[,i][which(scale(homes[,i]) < -5)] <- NA
		}
	}

```

```{r new and scale, include = TRUE, message = FALSE}

# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ...	create a few new columns
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

	dates <- paste(homes$yrsold, sprintf("%02d", homes$mosold), "01")
	homes$sale_date <- as.Date(dates, "%Y %m %d")
	
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ...	scale each column independently
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

#	for (i in 2 : length(homes))
#	{
#		if(class(homes[,i]) == "integer" || class(homes[,i]) == "numeric")
#		{
#			homes[,i] <- scale(homes[,i])
#		}
#	}

```

```{r plot base data, include = TRUE, message = FALSE}

# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ...	make some plots for numeric variables... linear, log_x, log_y, log_xy ...
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

	pdf ("homes_train_plots.pdf", width = 10, height = 7)

	par (mfrow = c (2, 3))
	for (i in 2:(length(homes)))
	{
		if(class(homes[,i]) == "integer" || class(homes[,i]) == "numeric" || class(homes[,i]) == "matrix")
		{
			plot (homes[,i], main = (names(homes[i])))
			hist(homes[,i])
			plot(log(homes$saleprice)  ~ homes[,i])
		}
	}

	par (mfrow = c (2, 2))
	for (i in 2:(length(homes)))
	{
		if(class(homes[,i]) == "factor")
		{
			plot_title <- names(homes[i])

			p <- ggplot(homes, aes(x = homes[,i], fill = homes[,i])) + geom_bar() + labs(title = plot_title)
			print(p)

			p <- ggplot(homes, aes(x = homes[,i], y = log(saleprice), fill = homes[,i])) + geom_boxplot() + labs(title = plot_title)
			print(p)
		}
	}	
		
			plot(log(homes$saleprice) ~ homes$sale_date)

	dev.off()
```

```{r first basic fit, echo = TRUE, message = FALSE} 

	for (i in 2:(length(homes)))
	{
		if(class(homes[,i]) == "integer" || class(homes[,i]) == "numeric" || class(homes[,i]) == "matrix")
		{
			fit <- lm(log(homes$saleprice) ~ homes[,i])
			
			print(sprintf(" ... %3d : %20s | %10s | r^2 = %8.3f | p-value = %12.4e",
						  i, names(homes[i]), class(homes[,i]), summary(fit)$r.squared, summary(fit)$coefficients[,4][2] ))
		}
	}

```

```{r impute, include = TRUE, message = FALSE}

# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ...	Impute NAs to functional value
# ...
# ...	--> for numerical variables - impute to mean value in column
# ...	--> for factor variables - create new factor "None"
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

		
	ncol <- length(homes)
	n_imp <- 0
	for (i in 1 : ncol)
	{
		if(class(homes[,i]) == "integer" || class(homes[,i]) == "numeric" || class(homes[,i]) == "matrix")
		{
			n_imp <- n_imp + 1
			homes[ncol+n_imp] <- 0
			homes[, (ncol+n_imp)][is.na (homes[,i])] <- 1
			
			new_name <- paste0("imp_", names(homes)[i])
			names(homes)[ncol+n_imp] <- new_name
			
			homes[,i][is.na (homes[,i])] <- mean(homes[,i], na.rm = TRUE)
			
		}
	}
	
	for (i in 1 : (length(homes)))
	{
		if(class(homes[,i]) == "factor")
		{
			levels <- levels(homes[,i])
			levels[length(levels) + 1] <- "None"
			homes[,i] <- factor(homes[,i], levels = levels)
			homes[,i][is.na (homes[,i])] <- "None"
		}
	}

```

```{r update r^2 after imputation, echo = TRUE, message = FALSE} 

	for (i in 2:(length(homes)))
	{
		if(class(homes[,i]) == "integer" || class(homes[,i]) == "numeric" || class(homes[,i]) == "matrix")
		{
			fit <- lm(log(homes$saleprice) ~ homes[,i])
			
			print(sprintf(" ... %3d : %20s | %10s | r^2 = %8.3f | p-value = %12.4e",
						  i, names(homes[i]), class(homes[,i]), summary(fit)$r.squared, summary(fit)$coefficients[,4][2] ))
		}
	}

```




``` {r visual removals, include = TRUE, message = FALSE}

# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ...	Columns to remove - based on visual inspection
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

# ...	save top 20 (based on r^2) for trial evaluation in SAS

	homes$log_lotfrontage <- log(homes$lotfrontage)
	homes$log_lotarea <- log(homes$lotarea)
	homes$log_grlivarea <- log(homes$grlivarea)
	homes$log_saleprice <- log(homes$saleprice)
	
	homes_sas_keep <- subset(homes,
			select = c(
			log_saleprice,
			bsmtfinsf1,
			bsmtfintype1,
			bsmtfullbath,
			bsmtqual,
			centralair,
			electrical,
			exterior1st,
			exterior2nd,
			exterqual,
			fireplacequ,
			fireplaces,
			foundation,
			fullbath,
			garagearea,
			garagecars,
			garagefinish,
			garagetype,
			grlivarea,
			halfbath,
			heatingqc,
			housestyle,
			kitchenqual,
			log_grlivarea,
			log_saleprice,
			log_lotarea,
			log_lotfrontage,
			lotshape,
			masvnrtype,
			mszoning,
			neighborhood,
			overallcond,
			overallqual,
			saletype,
			totalbsmtsf,
			totrmsabvgrd,
			x1stflrsf,
			x2ndflrsf,
			yearbuilt,
			yearremodadd,
# ..	- impute discretes
			imp_bsmtfinsf1,
			imp_bsmtfullbath,
			imp_fireplaces,
			imp_fullbath,
			imp_garagearea,
			imp_garagecars,
			imp_halfbath,
			imp_grlivarea,
			imp_saleprice,
			imp_lotarea,
			imp_lotfrontage,
			imp_overallcond,
			imp_overallqual,
			imp_totalbsmtsf,
			imp_totrmsabvgrd,
			imp_x1stflrsf,
			imp_x2ndflrsf,
			imp_yearbuilt,
			imp_yearremodadd))
	
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ... from the keep list , these are the factors :
# ...	bsmtfintype1, bsmtqual, centralair, electrical, exterior1st, exterior2nd, exterqual,
# ...	fireplacequ, foundation, garagefinish, garagetype, heatingqc, housestyle, kitchenqual,
# ...	lotshape, masvnrtype, mszoning, neighborhood, saletype, 
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
	
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ...	store reference data frame as base data set
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
	
		homes_subset_base <- homes_sas_keep

```


```{r save subsetted data, include = TRUE, message = FALSE}

# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ...	save data frame for SAS input file
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

	sas_dir <- "~/sas/SASUniversityEdition/myfolders/stats_ii"
	setwd(sas_dir)
	write.csv (homes_sas_keep, file = "training_set_cleaned.csv", row.names = FALSE)
	
	setwd(home_dir)
	setwd(data_dir)
	write.csv (homes_sas_keep, file = "training_set_cleaned.csv", row.names = FALSE)
	setwd(home_dir)
	

```
